- name: Install Google Chrome
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb


- name: Install Chrome driver
  ansible.builtin.unarchive:
    src: https://chromedriver.storage.googleapis.com/104.0.5112.79/chromedriver_linux64.zip
    dest: /usr/local/bin
    remote_src: yes


- name: Ensure Chrome driver is executable
  ansible.builtin.file:
    path: /usr/local/bin/chromedriver
    mode: 0755
