- name: Install Gnome Desktop and related packages
  ansible.builtin.package:
    name:
      - gnome-session
      - gdm3
      - ubuntu-desktop
    state: present


- name: Configure systemd to boot to graphical target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link


- name: Disable Software Updater popups
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/99update-notifier
    state: absent

- name: Disable screen lock
  become: false
  ansible.builtin.command:
    cmd: "gsettings set org.gnome.desktop.screensaver lock-enabled false"


- name: Disable screen energy saver
  become: false
  ansible.builtin.command:
    cmd: "gsettings set org.gnome.desktop.session idle-delay 0"


- name: Disable software update notifications
  become: false
  ansible.builtin.command:
    cmd: "gsettings set com.ubuntu.update-notifier no-show-notifications true"


- name: Disable release update prompts
  ansible.builtin.copy:
    src: release-upgrades
    dest: /etc/update-manager/release-upgrades


- name: Ensure Gnome .config directory exists
  ansible.builtin.file:
    path: /home/ubuntu/.config
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755


- name: Suppress welcome messages in Gnome
  ansible.builtin.copy:
    src: gnome-initial-setup-done
    dest: /home/ubuntu/.config/gnome-initial-setup-done
    owner: ubuntu
    group: ubuntu
    mode: 0644
