version: "2"
services:
  indico-web: &indico-web
    image: 378672356020.dkr.ecr.us-east-1.amazonaws.com/indico-web
    command: /opt/indico/run_indico.sh
    depends_on:
      - indico-redis
      - indico-celery
    ports:
      - "9090:59999"  # tcp socket port
    networks:
      - backend
      - frontend
    env_file:
      - indico.env
    volumes:
      - 'archive:/opt/indico/archive'
      - './data/log/nginx:/opt/indico/log/nginx'
      - 'customization:/opt/indico/custom'
      - 'static-files:/opt/indico/static'
    tmpfs:
      - /opt/indico/tmp
    volumes:
      - "coverage:/coverage"
  indico-static:
    image: 378672356020.dkr.ecr.us-east-1.amazonaws.com/indico-static
    networks:
      - frontend
  indico-celery:
    <<: *indico-web
    networks:
      - backend
    depends_on:
      - indico-redis
    command: /opt/indico/run_celery.sh
    ports: []
    volumes:
      - 'archive:/opt/indico/archive'
  indico-redis:
    image: redis
    networks:
      - backend
    volumes:
      - './data/redis:/data'
  indico-postgres:
    image: centos/postgresql-96-centos7
    networks:
      - backend
    environment:
      - POSTGRESQL_USER=indico
      - POSTGRESQL_PASSWORD=indicopass
      - POSTGRESQL_DATABASE=indico
      - POSTGRESQL_ADMIN_PASSWORD=indicopass
  indico-nginx:
    image: 378672356020.dkr.ecr.us-east-1.amazonaws.com/indico-nginx
    networks:
      - frontend
    env_file:
      - indico.env
    ports:
      - "8080:8080"
    volumes_from:
      - indico-web
volumes:
  archive:
  static-files:
  customization:
  coverage:
networks:
  backend: {}
  frontend: {}
