- name: Make project directory
  ansible.builtin.file:
    state: directory
    path: /data/studie/af
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Install TESTAR repository
  become: false
  ansible.builtin.git:
    repo: https://github.com/stsnel/TESTAR_dev.git
    dest: /data/studie/af/TESTAR_dev
    version: sietse-project-rebase-apr2022
    update: true
  # Ignore errors because of possible local modifications by TESTAR itself
  ignore_errors: true

- name: Build TESTAR
  become: false
  ansible.builtin.command:
    cmd: "./gradlew installDist"
    chdir: "/data/studie/af/TESTAR_dev"
