- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600


# Disable unattended upgrades so they don't interfere with experiments and playbook
- name: Disable unattended upgrades
  ansible.builtin.copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644


- name: Install Java dependencies for TESTAR and OrientDB
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - openjdk-11-jdk
      - openjdk-11-jre
      - gradle
    state: present


- name: Set user password
  ansible.builtin.user:
    name: ubuntu
    password: "{{ user_password }}"


# Workaround for NetworkManager issue - see https://stackoverflow.com/questions/53219008/ec2-ami-built-from-ubuntu-18-04-with-ubuntu-desktop-installed-is-unreachable
- name: Remove networking config
  become: yes
  become_user: root
  ansible.builtin.copy:
    content: ""
    dest: "/etc/NetworkManager/conf.d/10-globally-managed-devices.conf"
    force: true
-
