- name: Check out repository with SUT setups and scripts
  become: false
  ansible.builtin.git:
    repo: https://github.com/stsnel/lightweight-codeanalysis.git
    dest: /data/studie/af/lightweight-codeanalysis
  ignore_errors: true


- name: Pull CKAN Docker container images
  become: false
  ansible.builtin.shell:
    chdir: '/data/studie/af/lightweight-codeanalysis/suts/{{ item }}/run'
    cmd: docker-compose pull
  with_items:
    - ckan
    - ckan_plain
  when: download_sut_ckan


- name: Pull Indico Docker container images
  become: false
  ansible.builtin.shell:
    chdir: '/data/studie/af/lightweight-codeanalysis/suts/{{ item }}/run'
    cmd: docker-compose pull
  with_items:
    - indico
    - indico_plain
  when: download_sut_indico
