- name: Install Docker and Docker Compose
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - docker.io
      - docker-compose
    state: present


- name: Add user to Docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes


- name: Reset ssh connection to allow user changes to affect current user
  ansible.builtin.meta: reset_connection


- name: Authenticate Docker against AWS ECR
  become: false
  ansible.builtin.shell:
    cmd: "aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
