- name: Install TigerVNC packages
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - tigervnc-standalone-server
      - tigervnc-common
    state: present


- name: Configure TigerVNC credentials
  ansible.builtin.shell:
    cmd: printf "{{ tigervnc_password }}\n{{ tigervnc_password }}\n" | vncpasswd
    creates: /home/ubuntu/.vnc/passwd
    executable: /bin/bash


- name: Create VNC config directory
  ansible.builtin.file:
    path: /home/ubuntu/.vnc
    state: directory
    owner: ubuntu
    group: root
    mode: 0775


- name: Configure TigerVNC startup file
  ansible.builtin.copy:
    src: xstartup
    dest: /home/ubuntu/.vnc/xstartup
    mode: 0755
    owner: ubuntu
    group: ubuntu


- name: Upload script for starting VNC server
  ansible.builtin.copy:
    src: start-vncserver.sh
    dest: /home/ubuntu/start-vncserver.sh
    mode: 0755
    owner: ubuntu
    group: ubuntu
    
